### ISSUE TITLE
Does not work with sbt-web 1.4.0

### ISSUE THREAD

**Issue by codeape** [sbt/sbt-rjs#75]
It works fine with 1.3.0 but with 1.4.0 i get this:

`sbt cronusw/web-stage
[info] Loading global plugins from /home/codeape/.sbt/0.13/plugins
[info] Loading project definition from /home/codeape/src/git/cronus/project
[info] Set current project to cronus (in build file:/home/codeape/src/git/cronus/)
java.lang.NoSuchMethodError: com.typesafe.sbt.web.SbtWeb$.syncMappings(Ljava/io/File;Lscala/collection/Seq;Ljava/io/File;)Ljava/io/File;
    at com.typesafe.sbt.rjs.SbtRjs$$anonfun$runOptimizer$1$$anonfun$apply$9.apply(SbtRjs.scala:177)
    at com.typesafe.sbt.rjs.SbtRjs$$anonfun$runOptimizer$1$$anonfun$apply$9.apply(SbtRjs.scala:172)
    at scala.Function$$anonfun$chain$1$$anonfun$apply$1.apply(Function.scala:24)
    at scala.Function$$anonfun$chain$1$$anonfun$apply$1.apply(Function.scala:24)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
    at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
    at scala.Function$$anonfun$chain$1.apply(Function.scala:24)
    at com.typesafe.sbt.web.SbtWeb$$anonfun$projectSettings$44.apply(SbtWeb.scala:226)
    at com.typesafe.sbt.web.SbtWeb$$anonfun$projectSettings$44.apply(SbtWeb.scala:226)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (cronusw/*:webPipeline) java.lang.NoSuchMethodError: com.typesafe.sbt.web.SbtWeb$.syncMappings(Ljava/io/File;Lscala/collection/Seq;Ljava/io/File;)Ljava/io/File;
[error] Total time: 0 s, completed Oct 12, 2016 2:22:04 PM
`

**Comment by codeape** [comment]
It looks like there is a pullrequest for this to fix the problem: https://github.com/sbt/sbt-rjs/pull/67

**Comment by danielnixon** [comment]
Fixed in [my fork](https://github.com/danielnixon/sbt-rjs). Try `addSbtPlugin("org.danielnixon" % "sbt-rjs" % "1.0.9")`.

**Comment by codeape** [comment]
Thanks

**Comment by benmccann** [comment]
I've upgraded the project

**Comment by juanmirocks** [comment]
Didn't work for me for whatever reason -- However, used the latest `sbt-rjs` version as of now (`1.0.10`) and worked 🤷‍♂️ https://github.com/sbt/sbt-rjs

`addSbtPlugin("com.typesafe.sbt" % "sbt-rjs" % "1.0.10")`
